### ISSUE TITLE
Small networks not working

### ISSUE THREAD

**Issue by bosse89** [Hjorthmedh/Snudda#235]
I tried creating a 10 neuron network on the HPC Beskow and got a crash in the Place function:
###############################################
Traceback (most recent call last):
  File "/cfs/klemming/scratch/b/bobek/Projects/SnuddaProj03/snudda_env/bin/snudda", line 11, in <module>
    load_entry_point('snudda', 'console_scripts', 'snudda')()
  File "/cfs/klemming/scratch/b/bobek/Projects/SnuddaProj03/Snudda/snudda/cli.py", line 173, in snudda_cli
    actions[args.action](args)
  File "/cfs/klemming/scratch/b/bobek/Projects/SnuddaProj03/Snudda/snudda/core.py", line 176, in place_neurons
    sp.place()
  File "/cfs/klemming/scratch/b/bobek/Projects/SnuddaProj03/Snudda/snudda/place/place.py", line 142, in place
    self.parse_config()
  File "/cfs/klemming/scratch/b/bobek/Projects/SnuddaProj03/Snudda/snudda/place/place.py", line 454, in parse_config
    self.sort_neurons(sort_idx=self.cluster_neurons())
  File "/cfs/klemming/scratch/b/bobek/Projects/SnuddaProj03/Snudda/snudda/place/place.py", line 937, in cluster_neurons
    self.write_log(f"Redoing place:neuron_clustering, {np.count_nonzero(neuron_order < 0)} neurons unaccounted for",
TypeError: write_log() got an unexpected keyword argument 'is_error'
Something went wrong during placement, aborting!

############################################
Not sure what could be wrong but it might be after the latest morphology folder changes in september/october.
I attached a more full output: [slurm-7352509.txt](https://github.com/Hjorthmedh/Snudda/files/7481672/slurm-7352509.txt)

**Comment by bosse89** [comment]
The error only happens when running in serial, e.g. setting:
#SBATCH --nodes=1 
on Beskow

**Comment by Hjorthmedh** [comment]
I have increased n_trials to 5 in cluster_neurons (on doc branch). Let me know if the problem persists.
