### ISSUE TITLE
KeyError: 'populationUnitCorrelation'

### ISSUE THREAD

**Issue by antgon** [Hjorthmedh/Snudda#32]
Running the example simulation `StriatumScaffoldExample-tiny.ipynb` I get the error in the title upon executing input line [14] :

`!snudda input networks/tinySim --input snudda/data/config/input-tinytest-v6.json --time 1.0`.

The full output is:

```
Setting up inputs, assuming input.json exists
Using runID = 6
Writing input spikes to networks/tinySim/input-spikes.hdf5
Time = 1.0
Setting random seed: None
Using hdf5 version latest
Loading HDF5-file: networks/tinySim/network-pruned-synapses.hdf5
Loading input configuration from snudda/data/config/input-tinytest-v6.json
Reading neuron postions
Loading networks/tinySim/network-neuron-positions.hdf5
No SlurmID set, using -1
Load done. 0.00573493000047165
Reading config file networks/tinySim/network-config.json
IPYTHON_PROFILE = None
No IPYTHON_PROFILE environment variable set, running in serial
Running makePopulationUnitSpikeTrains
Running makeNeuronInputParallell
Traceback (most recent call last):
  File "/home/s06jg7/.local/bin/snudda", line 11, in <module>
    load_entry_point('snudda', 'console_scripts', 'snudda')()
  File "/home/s06jg7/Desktop/Snudda/snudda/cli.py", line 83, in snudda_cli
    actions[args.action](args)
  File "/home/s06jg7/Desktop/Snudda/snudda/core.py", line 297, in setup_input
    ni = SnuddaInput(input_config_file=input_config,
  File "/home/s06jg7/Desktop/Snudda/snudda/input.py", line 108, in __init__
    self.make_neuron_input_parallel()
  File "/home/s06jg7/Desktop/Snudda/snudda/input.py", line 383, in make_neuron_input_parallel
    p_keep_list.append(np.sqrt(input_inf["populationUnitCorrelation"]))
KeyError: 'populationUnitCorrelation'
```

**Comment by StrongSpoon** [comment]
use input-tinytest-v8.json instead

**Comment by HolyLow** [comment]
> use input-tinytest-v8.json instead

It works! Thanks a lot lol
